# Generated by Django 3.2 on 2022-07-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('abstructbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.abstructbasemodel')),
                ('name', models.CharField(max_length=70)),
                ('type', models.CharField(choices=[('Chineese', 'Chineese'), ('South Indian', 'South Indian')], max_length=30)),
                ('description', models.CharField(max_length=150)),
            ],
            bases=('employee.abstructbasemodel',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('abstructbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.abstructbasemodel')),
                ('name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
            bases=('employee.abstructbasemodel',),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('abstructbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.abstructbasemodel')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THUR', 'Thursday'), ('FRI', 'Friday')], max_length=10)),
                ('vote', models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1)])),
                ('item', models.ManyToManyField(to='restaurant.Item')),
                ('restaurant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            bases=('employee.abstructbasemodel',),
        ),
    ]
