# Generated by Django 3.2 on 2022-07-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20220729_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='vote',
            field=models.CharField(choices=[(-1, 'Dislike'), (0, 'Neutral'), (1, 'Like')], default=-1, max_length=10),
        ),
    ]
