# Generated by Django 3.2 on 2022-08-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_ratings_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='rate',
        ),
        migrations.AlterField(
            model_name='ratings',
            name='vote',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Mid'), (3, 'High')], default='Low', max_length=10),
        ),
    ]
